name: BuildRelease

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - id: set-version
      run: |
        version=$(cat ./VERSION | python -c 'import sys, json; f=open("./VERSION");print(json.loads(f.read())["buildVersion"])')
        echo "::set-output name=version::$version"
        
    - name: Python setup
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        if [ -f ./requirements.txt ]; then pip3 install -r ./requirements.txt; fi
        
    - name: Create DeepSea Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: | 
        python ./autobuild.py -gt="$GITHUB_TOKEN"

    - name: Generate changelog
      id: changelog
      uses: metcalfc/changelog-generator@v0.4.4
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "./*zip"
        name: "Release v${{ steps.set-version.outputs.version }}"
        body: "${{ steps.changelog.outputs.changelog }}"
        tag: "v${{ steps.set-version.outputs.version }}"
        token: ${{ secrets.GITHUB_TOKEN }}